In [2]:
import pandas as pd
file_name = "https://people.sc.fsu.edu/~jburkardt/data/csv/homes.csv"
df = pd.read_csv(file_name)

In [3]:
df.reset_index().values

array([[0.0000e+00, 1.4200e+02, 1.6000e+02, 2.8000e+01, 1.0000e+01,
        5.0000e+00, 3.0000e+00, 6.0000e+01, 2.8000e-01, 3.1670e+03],
       [1.0000e+00, 1.7500e+02, 1.8000e+02, 1.8000e+01, 8.0000e+00,
        4.0000e+00, 1.0000e+00, 1.2000e+01, 4.3000e-01, 4.0330e+03],
       [2.0000e+00, 1.2900e+02, 1.3200e+02, 1.3000e+01, 6.0000e+00,
        3.0000e+00, 1.0000e+00, 4.1000e+01, 3.3000e-01, 1.4710e+03],
       [3.0000e+00, 1.3800e+02, 1.4000e+02, 1.7000e+01, 7.0000e+00,
        3.0000e+00, 1.0000e+00, 2.2000e+01, 4.6000e-01, 3.2040e+03],
       [4.0000e+00, 2.3200e+02, 2.4000e+02, 2.5000e+01, 8.0000e+00,
        4.0000e+00, 3.0000e+00, 5.0000e+00, 2.0500e+00, 3.6130e+03],
       [5.0000e+00, 1.3500e+02, 1.4000e+02, 1.8000e+01, 7.0000e+00,
        4.0000e+00, 3.0000e+00, 9.0000e+00, 5.7000e-01, 3.0280e+03],
       [6.0000e+00, 1.5000e+02, 1.6000e+02, 2.0000e+01, 8.0000e+00,
        4.0000e+00, 3.0000e+00, 1.8000e+01, 4.0000e+00, 3.1310e+03],
       [7.0000e+00, 2.0700e+02, 2.2500e+0

In [4]:
df.values

array([[1.4200e+02, 1.6000e+02, 2.8000e+01, 1.0000e+01, 5.0000e+00,
        3.0000e+00, 6.0000e+01, 2.8000e-01, 3.1670e+03],
       [1.7500e+02, 1.8000e+02, 1.8000e+01, 8.0000e+00, 4.0000e+00,
        1.0000e+00, 1.2000e+01, 4.3000e-01, 4.0330e+03],
       [1.2900e+02, 1.3200e+02, 1.3000e+01, 6.0000e+00, 3.0000e+00,
        1.0000e+00, 4.1000e+01, 3.3000e-01, 1.4710e+03],
       [1.3800e+02, 1.4000e+02, 1.7000e+01, 7.0000e+00, 3.0000e+00,
        1.0000e+00, 2.2000e+01, 4.6000e-01, 3.2040e+03],
       [2.3200e+02, 2.4000e+02, 2.5000e+01, 8.0000e+00, 4.0000e+00,
        3.0000e+00, 5.0000e+00, 2.0500e+00, 3.6130e+03],
       [1.3500e+02, 1.4000e+02, 1.8000e+01, 7.0000e+00, 4.0000e+00,
        3.0000e+00, 9.0000e+00, 5.7000e-01, 3.0280e+03],
       [1.5000e+02, 1.6000e+02, 2.0000e+01, 8.0000e+00, 4.0000e+00,
        3.0000e+00, 1.8000e+01, 4.0000e+00, 3.1310e+03],
       [2.0700e+02, 2.2500e+02, 2.2000e+01, 8.0000e+00, 4.0000e+00,
        2.0000e+00, 1.6000e+01, 2.2200e+00, 5.1580e+03],


In [6]:
df.to_numpy()

array([[1.4200e+02, 1.6000e+02, 2.8000e+01, 1.0000e+01, 5.0000e+00,
        3.0000e+00, 6.0000e+01, 2.8000e-01, 3.1670e+03],
       [1.7500e+02, 1.8000e+02, 1.8000e+01, 8.0000e+00, 4.0000e+00,
        1.0000e+00, 1.2000e+01, 4.3000e-01, 4.0330e+03],
       [1.2900e+02, 1.3200e+02, 1.3000e+01, 6.0000e+00, 3.0000e+00,
        1.0000e+00, 4.1000e+01, 3.3000e-01, 1.4710e+03],
       [1.3800e+02, 1.4000e+02, 1.7000e+01, 7.0000e+00, 3.0000e+00,
        1.0000e+00, 2.2000e+01, 4.6000e-01, 3.2040e+03],
       [2.3200e+02, 2.4000e+02, 2.5000e+01, 8.0000e+00, 4.0000e+00,
        3.0000e+00, 5.0000e+00, 2.0500e+00, 3.6130e+03],
       [1.3500e+02, 1.4000e+02, 1.8000e+01, 7.0000e+00, 4.0000e+00,
        3.0000e+00, 9.0000e+00, 5.7000e-01, 3.0280e+03],
       [1.5000e+02, 1.6000e+02, 2.0000e+01, 8.0000e+00, 4.0000e+00,
        3.0000e+00, 1.8000e+01, 4.0000e+00, 3.1310e+03],
       [2.0700e+02, 2.2500e+02, 2.2000e+01, 8.0000e+00, 4.0000e+00,
        2.0000e+00, 1.6000e+01, 2.2200e+00, 5.1580e+03],


In [7]:
df.Sell.to_numpy()

array([142, 175, 129, 138, 232, 135, 150, 207, 271,  89, 153,  87, 234,
       106, 175, 165, 166, 136, 148, 151, 180, 293, 167, 190, 184, 157,
       110, 135, 567, 180, 183, 185, 152, 148, 152, 146, 170, 127, 265,
       157, 128, 110, 123, 212, 145, 129, 143, 247, 111, 133])

In [15]:
c = df.columns
array = df.values

In [16]:
df = pd.DataFrame(array)

In [9]:
df.head()

0      1     2     3    4    5     6     7       8
0  142.0  160.0  28.0  10.0  5.0  3.0  60.0  0.28  3167.0
1  175.0  180.0  18.0   8.0  4.0  1.0  12.0  0.43  4033.0
2  129.0  132.0  13.0   6.0  3.0  1.0  41.0  0.33  1471.0
3  138.0  140.0  17.0   7.0  3.0  1.0  22.0  0.46  3204.0
4  232.0  240.0  25.0   8.0  4.0  3.0   5.0  2.05  3613.0

In [17]:
df = pd.DataFrame(array,columns=c)

In [18]:
df.head()

Sell   "List"   "Living"   "Rooms"   "Beds"   "Baths"   "Age"   "Acres"  \
0  142.0    160.0       28.0      10.0      5.0       3.0    60.0      0.28   
1  175.0    180.0       18.0       8.0      4.0       1.0    12.0      0.43   
2  129.0    132.0       13.0       6.0      3.0       1.0    41.0      0.33   
3  138.0    140.0       17.0       7.0      3.0       1.0    22.0      0.46   
4  232.0    240.0       25.0       8.0      4.0       3.0     5.0      2.05   

    "Taxes"  
0    3167.0  
1    4033.0  
2    1471.0  
3    3204.0  
4    3613.0